# Generated by Django 4.1.4 on 2023-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_eventdetails_rename_user_hod_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_member",
            field=models.BooleanField(default=False),
        ),
    ]
