# Generated by Django 4.1.4 on 2023-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_student_is_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="gender",
            field=models.CharField(default="male", max_length=6),
        ),
        migrations.AddField(
            model_name="hod",
            name="gender",
            field=models.CharField(default="male", max_length=6),
        ),
        migrations.AddField(
            model_name="labassistant",
            name="gender",
            field=models.CharField(default="male", max_length=6),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(default="male", max_length=6),
        ),
    ]
