# Generated by Django 4.1.4 on 2023-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_department_name_alter_division_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendardetails",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventdetails",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hod", name="is_active", field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="labassistant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
