import { atom } from "jotai";

export const sideBarAtom = atom(false);

// Only for temporary purposes
export const tempUserName = atom({ name: "Shubham Bhogayata", gender: "male" });
export const currentUserId = atom(1);

export const tempGrpDetails = [
	{
		id: 2,
		project_name: "Temp",
		project_desc: "PROCOM is an innovative website designed to provide users with a comprehensive platform for comparing products across various categories, including electronics, sports, apps, and more. The website also serves as an e-commerce platform, integrating multiple popular online retailers such as Amazon, Flipkart, Croma, and others. In addition to facilitating product comparisons, PROCOM aims to empower developers by offering an Admin panel and creating APIs for over 20 different platforms. Furthermore, the project includes the development of a unique system that enables developers to create web scrapers from the website's user interface, allowing them to utilize any website as a real-time API. Key Features: Product Comparison: PROCOM offers users a centralized platform to compare products from diverse categories. The website provides comprehensive information, including specifications, prices, user reviews, and ratings, assisting users in making informed purchase decisions. E-commerce Integration: The platform seamlessly integrates with popular e-commerce platforms, including Amazon, Flipkart, Croma, and more. Users can browse products from these platforms directly on PROCOM, providing a convenient and streamlined shopping experience. Developer's Admin Panel: PROCOM provides a dedicated admin panel for developers. This panel offers a range of features and tools for managing and enhancing the website's functionality. Developers can access and modify various aspects of the platform, including APIs, data integration, scraping settings, and user management. API Development: The project involves the creation of APIs for more than 20 different platforms. These APIs enable seamless data integration between PROCOM and the supported platforms, ensuring up-to-date information on products, prices, availability, and more. Developers can leverage these APIs to enhance their own applications and services. Web Scraper Creation: PROCOM offers a user-friendly interface that empowers developers to create their own web scrapers. This unique system enables developers to extract data from any website and utilize it as a real-time API. The web scraper creation tool allows for customization and configuration based on individual requirements. Benefits: Comprehensive Product Comparison: Users can conveniently compare products from different categories and make well-informed purchasing decisions. Enhanced E-commerce Experience: Integration with popular e-commerce platforms simplifies the shopping process by providing a unified interface for browsing and purchasing products. Developer Empowerment: The inclusion of an admin panel and API development enables developers to extend the functionality of PROCOM and integrate it into their own applications and services. Versatile Web Scraping Capabilities: The web scraper creation system allows developers to access data from any website, expanding the possibilities for real-time data integration and utilization. Overall, PROCOM is a dynamic website that brings together product comparison and e-commerce functionalities while empowering developers to enhance and customize the platform. By offering a wide range of features and tools, PROCOM aims to provide an intuitive and comprehensive experience for both users and developers.",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 1,
		mentor_name: "Violante Loomis",
		mentor_email: "fgreensite0@icq.com",
		group_leader: "Fairleigh Greensite",
		group_members: [
			"Chrissy Staniforth",
			"Barron Byard",
			"Terry Schwandt",
		],
	},
	{
		id: 3,
		project_name: "Cardguard",
		project_desc: "Walked into lamppost, initial encounter",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 2,
		mentor_name: "Lorilyn Pullen",
		mentor_email: "gcrowhurst1@printfriendly.com",
		group_leader: "Gerri Crowhurst",
		group_members: [
			"Carolyn Pitkeathly",
			"Aldus Rylance",
		],
	},
	{
		id: 4,
		project_name: "Daltfresh",
		project_desc: "Choroidal degeneration, unspecified, right eye",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 3,
		mentor_name: "Dorree Lammert",
		mentor_email: "ptrevaskis2@desdev.cn",
		group_leader: "Pete Trevaskis",
		group_members: [
			"Immanuel Grzeskowski",
			"Vanya Walford",
			"Tatiania Hutcheon",
			"Tamiko Doyley",
		],
	},
	{
		id: 5,
		project_name: "Bitwolf",
		project_desc:
			"Complete lesion of L5 level of lumbar spinal cord, sequela",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 4,
		mentor_name: "Chane O'Farrell",
		mentor_email: "aadshead3@mail.ru",
		group_leader: "Ardis Adshead",
		group_members: [
			"Elnore Ransley",
			"Simeon Bech",
			"Gypsy Simeone",
			"William Clooney",
		],
	},
	{
		id: 6,
		project_name: "Aerified",
		project_desc:
			"External constriction of left little finger, initial encounter",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 5,
		mentor_name: "Klarrisa Nealy",
		mentor_email: "hwrathall4@privacy.gov.au",
		group_leader: "Heriberto Wrathall",
		group_members: [
			"Brantley Speight",
			"Caesar Ashley",
		],
	},
	{
		id: 7,
		project_name: "Fixflex",
		project_desc:
			"Diffuse traumatic brain injury without loss of consciousness, sequela",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 6,
		mentor_name: "Erinna Pengilly",
		mentor_email: "ujarrel5@tinyurl.com",
		group_leader: "Ulberto Jarrel",
		group_members: [
			"Latrena MacEvilly",
			"Leena Shaxby",
		],
	},
	{
		id: 8,
		project_name: "Andalax",
		project_desc: "Assault by pushing from high place, sequela",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 7,
		mentor_name: "Moreen Edland",
		mentor_email: "yguislin6@techcrunch.com",
		group_leader: "Yvette Guislin",
		group_members: [
			"Adrienne Baskett",
			"Charla Fancy",
		],
	},
	{
		id: 9,
		project_name: "Otcom",
		project_desc: "Left upper quadrant abdominal rigidity",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 8,
		mentor_name: "Glenda Semrad",
		mentor_email: "ezoren7@gov.uk",
		group_leader: "Eirena Zoren",
		group_members: [
			"Lacie Farnish",
			"Carolee Siggery",
			"De Beneditti",
			"Wait Guille",
		],
	},
	{
		id: 10,
		project_name: "Keylex",
		project_desc:
			"Nondisplaced fracture of neck of other metacarpal bone, initial encounter for closed fracture",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 9,
		mentor_name: "Bruce Covey",
		mentor_email: "zcholomin8@un.org",
		group_leader: "Zaneta Cholomin",
		group_members: [
			"Nani Fairbrace",
			"Merwin Tomaselli",
			"Marian Bocken",
		],
	},
	{
		id: 11,
		project_name: "Alpha",
		project_desc:
			"Onset (spontaneous) of labor after 37 completed weeks of gestation but before 39 completed weeks gestation, with delivery by (planned) cesarean section",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 10,
		mentor_name: "Kahlil Eaglen",
		mentor_email: "ulutas9@samsung.com",
		group_leader: "Urbanus Lutas",
		group_members: [
			"Christy Laval",
			"Mikkel Curston",
			"Olly Ettridge",
			"Haze Nowland",
		],
	},
	{
		id: 12,
		project_name: "Voltsillam",
		project_desc:
			"Pedal cycle driver injured in collision with two- or three-wheeled motor vehicle in nontraffic accident, initial encounter",
		project_techs: [
			"React",
			"Next JS 13",
			"TypeScript",
			"Tailwind CSS",
			"Django",
		],
		project_tasks: ["Asd", "ASDasdgdlksfadkfd;kasdals", "asdajoiiiiiiiiiiiiiiiiiiiiiasdad add ad adasdad adsd sdkajskldjaklsjdklajdsj aklsdjklasjdlkajosdjaojsdlkajskdp ajsdpkaj s;kldjlasldla"],
		mentor_id: 11,
		mentor_name: "Butch Ducket",
		mentor_email: "abonifasa@ezinearticles.com",
		group_leader: "Alfy Bonifas",
		group_members: [
			"Eunice Goskar",
			"Birch Pheazey,Mile Prowting",
			"Ryon Burtenshaw",
		],
	},
	// {
	// 	"id": 13,
	// 	"project_name": "Stringtough",
	// 	"project_desc": "Strain of flexor muscle, fascia and tendon of right middle finger at wrist and hand level, sequela",
	// 	"project_techs": [{}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}],
	// 	"mentor_id": 12,
	// 	"mentor_name": "Dorelle Wofenden",
	// 	"mentor_email": "klendremb@usgs.gov",
	// 	"group_leader": "Kristine Lendrem",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 14,
	// 	"project_name": "Asoka",
	// 	"project_desc": "Primary blast injury of transverse colon, sequela",
	// 	"project_techs": [{}, {}, {}],
	// 	"project_tasks": [{}, {}],
	// 	"mentor_id": 13,
	// 	"mentor_name": "Marjorie Bettam",
	// 	"mentor_email": "mmcgraylec@answers.com",
	// 	"group_leader": "Mathew McGrayle",
	// 	"group_members": [{}, {}]
	// },
	// {
	// 	"id": 15,
	// 	"project_name": "Cookley",
	// 	"project_desc": "Drug induced retention of urine",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}],
	// 	"mentor_id": 14,
	// 	"mentor_name": "Bradly Krink",
	// 	"mentor_email": "nleurend@nationalgeographic.com",
	// 	"group_leader": "Nollie Leuren",
	// 	"group_members": [{}, {}, {}, {}]
	// },
	// {
	// 	"id": 16,
	// 	"project_name": "Latlux",
	// 	"project_desc": "Laceration without foreign body of pharynx and cervical esophagus, sequela",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}],
	// 	"mentor_id": 15,
	// 	"mentor_name": "Barde Lusty",
	// 	"mentor_email": "shuggette@amazon.co.jp",
	// 	"group_leader": "Selestina Huggett",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 17,
	// 	"project_name": "Sub-Ex",
	// 	"project_desc": "Major laceration of right pulmonary blood vessels, sequela",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}, {}],
	// 	"mentor_id": 16,
	// 	"mentor_name": "Melvin Selborne",
	// 	"mentor_email": "olererf@upenn.edu",
	// 	"group_leader": "Olly Lerer",
	// 	"group_members": [{}, {}]
	// },
	// {
	// 	"id": 18,
	// 	"project_name": "Home Ing",
	// 	"project_desc": "Continuing pregnancy after spontaneous abortion of one fetus or more, second trimester, fetus 3",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}, {}],
	// 	"mentor_id": 17,
	// 	"mentor_name": "Silvana Flegg",
	// 	"mentor_email": "awithropg@seesaa.net",
	// 	"group_leader": "Alla Withrop",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 19,
	// 	"project_name": "Ronstring",
	// 	"project_desc": "Unspecified soft tissue disorder related to use, overuse and pressure of hand",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}],
	// 	"mentor_id": 18,
	// 	"mentor_name": "Ellswerth Mattin",
	// 	"mentor_email": "oshuggh@chronoengine.com",
	// 	"group_leader": "Oneida Shugg",
	// 	"group_members": [{}, {}]
	// },
	// {
	// 	"id": 20,
	// 	"project_name": "Matsoft",
	// 	"project_desc": "Sprain of tarsal ligament of unspecified foot, initial encounter",
	// 	"project_techs": [{}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}],
	// 	"mentor_id": 19,
	// 	"mentor_name": "Chic Pentecust",
	// 	"mentor_email": "othaini@naver.com",
	// 	"group_leader": "Olenka Thain",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 21,
	// 	"project_name": "Quo Lux",
	// 	"project_desc": "Displaced fracture of hook process of hamate [unciform] bone, unspecified wrist, subsequent encounter for fracture with malunion",
	// 	"project_techs": [{}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}],
	// 	"mentor_id": 20,
	// 	"mentor_name": "Korney Mauvin",
	// 	"mentor_email": "nmacchaellj@cargocollective.com",
	// 	"group_leader": "Nicholle MacChaell",
	// 	"group_members": [{}, {}]
	// },
	// {
	// 	"id": 22,
	// 	"project_name": "Zontrax",
	// 	"project_desc": "Nondisplaced fracture of shaft of third metacarpal bone, right hand, initial encounter for closed fracture",
	// 	"project_techs": [{}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}, {}],
	// 	"mentor_id": 21,
	// 	"mentor_name": "Charlie Pearcey",
	// 	"mentor_email": "acuellk@mac.com",
	// 	"group_leader": "Artie Cuell",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 23,
	// 	"project_name": "Ronstring",
	// 	"project_desc": "Poisoning by loop [high-ceiling] diuretics, undetermined, sequela",
	// 	"project_techs": [{}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}, {}],
	// 	"mentor_id": 22,
	// 	"mentor_name": "Idalia Sydry",
	// 	"mentor_email": "kstainlandl@jalbum.net",
	// 	"group_leader": "Kathryn Stainland",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 24,
	// 	"project_name": "Sonair",
	// 	"project_desc": "Type III occipital condyle fracture, unspecified side, subsequent encounter for fracture with nonunion",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}],
	// 	"mentor_id": 23,
	// 	"mentor_name": "Erna Oriel",
	// 	"mentor_email": "amucklom@blogtalkradio.com",
	// 	"group_leader": "Abba Mucklo",
	// 	"group_members": [{}, {}, {}]
	// },
	// {
	// 	"id": 25,
	// 	"project_name": "Asoka",
	// 	"project_desc": "Displaced bicondylar fracture of right tibia, initial encounter for open fracture type I or II",
	// 	"project_techs": [{}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}],
	// 	"mentor_id": 24,
	// 	"mentor_name": "Lynea Gidley",
	// 	"mentor_email": "brushfordn@buzzfeed.com",
	// 	"group_leader": "Brnaba Rushford",
	// 	"group_members": [{}, {}, {}, {}]
	// },
	// {
	// 	"id": 26,
	// 	"project_name": "Voltsillam",
	// 	"project_desc": "3-part fracture of surgical neck of right humerus, sequela",
	// 	"project_techs": [{}, {}, {}, {}, {}, {}],
	// 	"project_tasks": [{}, {}, {}, {}, {}, {}],
	// 	"mentor_id": 25,
	// 	"mentor_name": "Gene Sulland",
	// 	"mentor_email": "jchasmoro@chron.com",
	// 	"group_leader": "Jamima Chasmor",
	// 	"group_members": [{}, {}, {}]
	// }
];
