# Generated by Django 4.1.4 on 2023-08-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_student_is_member"),
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader",
                to="main.student",
            ),
        ),
    ]
